# Specify a command to be executed
# like `/bin/bash -l`, `ls`, or any other commands
# the default is bash for Linux
# or powershell.exe for Windows
command: null

# Specify the current working directory path
# the default is the current working directory path
cwd: null

# Export additional ENV variables
env:
  recording: true

# Explicitly set the number of columns
# or use `auto` to take the current
# number of columns of your shell
cols: 120

# Explicitly set the number of rows
# or use `auto` to take the current
# number of rows of your shell
rows: 45

# Amount of times to repeat GIF
# If value is -1, play once
# If value is 0, loop indefinitely
# If value is a positive number, loop n times
repeat: 0

# Quality
# 1 - 100
quality: 100

# Delay between frames in ms
# If the value is `auto` use the actual recording delays
frameDelay: auto

# Maximum delay between frames in ms
# Ignored if the `frameDelay` isn't set to `auto`
# Set to `auto` to prevent limiting the max idle time
maxIdleTime: 2000

# The surrounding frame box
# The `type` can be null, window, floating, or solid`
# To hide the title use the value null
# Don't forget to add a backgroundColor style with a null as type
frameBox:
  type: window
  title: PowerShell
  style:
    border: 0px solid rgb(0, 0, 0)
    boxShadow: 8px 8px 16px grey
    #margin: 0px 10px 20px 30px

# Add a watermark image to the rendered gif
# You need to specify an absolute path for
# the image on your machine or a URL, and you can also
# add your own CSS styles
watermark:
  imagePath: null
 # style:
    # position: absolute
    # right: 15px
    # bottom: 15px
    # width: 100px
    # opacity: 0.9

# Cursor style can be one of
# `block`, `underline`, or `bar`
cursorStyle: underline

# Font family
# You can use any font that is installed on your machine
# in CSS-like syntax
fontFamily: "Consolas, Lucida Console, Monaco, Ubuntu Mono, Monospace"

# The size of the font
fontSize: 14

# The height of lines
lineHeight: 1

# The spacing between letters
letterSpacing: 0

# Theme
theme:
  background: "#282a48"
  foreground: "#eeedf0"
  cursor: "#c7c7c7"
  black: "#282a48"
  red: "#bf0000"
  green: "#008000"
  yellow: "#f2c800"
  blue: "#4472c4"
  magenta: "#8a3cc4"
  cyan: "#ff7e00"
  white: "#c0c0c0"
  brightBlack: "#808080"
  brightRed: "#fe2020"
  brightGreen: "#92d050"
  brightYellow: "#f2f200"
  brightBlue: "#3d94f3"
  brightMagenta: "#fe8cff"
  brightCyan: "#42e0d1"
  brightWhite: "#a8a8a8"
